OrdererOrgs:
  - Name: Orderer
    Domain: cache.com
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
PeerOrgs:
  - Name: PRIVI
    Domain: privi.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1