OrdererOrgs:
  - Name: cache
    Domain: cache.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: privi
    Domain: privi.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1